### ISSUE TITLE
No solution var.x is None

### ISSUE THREAD

**Issue by zealfory** [wbwseeker/meteor#2]
Try :
   hypothsis = "The patient was admitted due to type 2 diabetes mellitus, and began to receive subcutaneous injection of liraglutide injection (0.6 mg/day) at 9: 00 on 09-Jun-2020. About 1 hour later, around 10: 00 on the same day, the patient developed nausea, which lasted for about 2 hours. No drug treatment was taken, during which the patient did not eat."
    reference = "The patient was admitted to hospital for type 2 diabetes mellitus, and liraglutide injection (0.6 mg/day) was administered subcutaneously at 9 o 'clock on June 9th, 2020. About 1 hour later, nausea occured at around 10 o' clock that day, lasting about 2 hours. No drug treatment measures were taken, during which the patient did not eat."

Then got:
    return [match for match, var in match_vars.items() if var.x >= 0.99]  # todo ??
TypeError: '>=' not supported between instances of 'NoneType' and 'float'

Do you know how to resolve this problem, please?

**Comment by wbwseeker** [comment]
Hey,
thanks a lot for pointing this out! There was indeed a bug in the computation of the alignment.
I pushed a fix, please check and let me know whether this solves your problem.

**Comment by zealfory** [comment]
> Hey,
> thanks a lot for pointing this out! There was indeed a bug in the computation of the alignment.
> I pushed a fix, please check and let me know whether this solves your problem.

Solved. Thanks a lot ^_^
